languaje: generic

sudo: required
services:
    - docker

before_install:
    - docker build -t fibonacciclienttest -f ./client/Dockerfile.dev ./client

script:
    - docker run -e CI=true fibonacciclienttest npm test -- --coverage

after_succes:
    - docker build -t Bryandrm/fibonacciclient ./client
    - docker build -t Bryandrm/fibonaccinginx ./nginx
    - docker build -t Bryandrm/fibonacciserver ./server
    - docker build -t Bryandrm/fibonacciworker ./worker

    #log in to the docker cli

    - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin

    #push images to docker hub

    - docker push Bryandrm/fibonacciclient
    - docker push Bryandrm/fibonaccinginx
    - docker push Bryandrm/fibonacciserver
    - docker push Bryandrm/fibonacciworker
