languaje: generic

sudo: required
services:
    - docker

before_install:
    - docker build -t fibonacciclienttest -f ./client/Dockerfile.dev ./client

script:
    - docker run -e CI=true fibonacciclienttest npm test -- --coverage

after_succes:
    - docker build -t fibonacciclient ./client
    - docker build -t fibonaccinginx ./nginx
    - docker build -t fibonacciserver ./server
    - docker build -t fibonacciworker ./worker

    #log in to the docker cli

    - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin

    #push images to docker hub

    - docker push fibonacciclient
    - docker push fibonaccinginx
    - docker push fibonacciserver
    - docker push fibonacciworker
